os: osx
osx_image: xcode12

# Clean and don't fail
install:
  - brew install go hugo
  - rm -rf public || exit 0

# Build the website
script:
  - git submodule update --init --recursive
  - hugo -v

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  repo: czhong720/czhong720.github.io
  target-branch: gh-pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
